### ISSUE TITLE
Can I speed up th Unfollows?

### ISSUE THREAD

**Issue by cristianneely** [andrewsegas/instaboost#26]
> Fill in all requirements *before* submitting an issue.

- [x] This is a checked box. **Do not leave spaces around the `x`!**

## Issue with the same problem
- [x] I have searched for other issues with the same problem.

## Hosting
- [x] Is it a local machine?

#### Select one:
- [ ] Bug
- [x] Feature Request
- [ ] Technical Help
- [ ] Other

### Operating System? (include version)
MAC / Windows / Linux / Android
Windows 10

## Running Mode
- [x] instaboost.exe
- [ ] example.py , mode (1,2,3,4 or 5)?
- [ ] instaboost.py
- [ ] Other

## Python Version?
2 / x3

## Description

I want to know if its possible to speed up the unfollows. I am running with the .exe and only selecting unfollows, but it unfollows like 1 user every 2 or 3 minutes. Is this supose to be like this?

Thanks

```

```

**Comment by andrewsegas** [comment]
Hi @cristianneely yes, it is.
If you check the documentation it is Unfollow per day, if you put 2 will be 12 hours for one, and 12 hours after the second
but the software cares about your safety as well, so is dangerous to unfollow very fast, usually is better to do it manually in your phone, otherwise you can be banned
